/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makatihomes;

import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.io.FileOutputStream;
import javax.swing.*;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.applet.*;  
import java.awt.*;  
import static java.lang.Thread.sleep;
import java.util.*;  
import java.text.*;  
import java.util.Date;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author GameDev
 */
public class BuildingUnits extends javax.swing.JInternalFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form BuildingUnits
     */
    public BuildingUnits() {
        initComponents();
        conn = javaconnect.connectdb();
        removetitlebar();
        Updatetable();
        CurrentDate();
        UnitCombo();
    }
        public void removetitlebar(){
        putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }
        public void CurrentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        String dates ="Date:"+" "+year+"-"+(month+1)+"-"+day;
        
    }
     private void UnitRoomTable(){
        try{
            if(unitcombo.getSelectedItem().toString().equals("Show All Units")){           
            String sql = "Select buildingName as Building,unitNumber as UnitNumber from buildingunits";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            unittable.setModel(DbUtils.resultSetToTableModel(rs));    
            }else{
            String comboid = unitcombo.getSelectedItem().toString();
            String sql = "Select buildingName as Building,unitNumber as UnitNumber from buildingunits where buildingName = '"+comboid+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            unittable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    private void UnitCombo(){
       
        try{
            
            String sql = "select * from buildings";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery(sql);  
            while(rs.next()){
                String buildingname = rs.getString("buildingName");               
                unitcombo.addItem(buildingname);  
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
    }
        private void Updatetable(){
        try{
        String sql = "select buildingID as BuildingID, buildingName as Building from buildings ";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        buildingtable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        ButtonHolder = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MainHolder = new javax.swing.JPanel();
        Building = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        building = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        buildingtable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Unit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unitroom = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        unittable = new javax.swing.JTable();
        unitcombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        Background.setBackground(new java.awt.Color(255, 255, 255));

        ButtonHolder.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makatihomes/Images/building_1.png"))); // NOI18N
        jButton1.setText("Building");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makatihomes/Images/room_1.png"))); // NOI18N
        jButton2.setText("Unit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Building and Unit");

        javax.swing.GroupLayout ButtonHolderLayout = new javax.swing.GroupLayout(ButtonHolder);
        ButtonHolder.setLayout(ButtonHolderLayout);
        ButtonHolderLayout.setHorizontalGroup(
            ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonHolderLayout.createSequentialGroup()
                .addGroup(ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonHolderLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6))
                    .addGroup(ButtonHolderLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ButtonHolderLayout.setVerticalGroup(
            ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonHolderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainHolder.setBackground(new java.awt.Color(255, 255, 255));
        MainHolder.setLayout(new java.awt.CardLayout());

        Building.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Building Name:");

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makatihomes/Images/units.png"))); // NOI18N
        jButton3.setText("Add Building");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buildingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(buildingtable);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Add Building");

        javax.swing.GroupLayout BuildingLayout = new javax.swing.GroupLayout(Building);
        Building.setLayout(BuildingLayout);
        BuildingLayout.setHorizontalGroup(
            BuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildingLayout.createSequentialGroup()
                .addGroup(BuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuildingLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(BuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BuildingLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(building, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))))
                    .addGroup(BuildingLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BuildingLayout.setVerticalGroup(
            BuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuildingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addGroup(BuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(building, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainHolder.add(Building, "card2");

        Unit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Unit Building:");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Unit Room:");

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makatihomes/Images/units.png"))); // NOI18N
        jButton4.setText("Add Room");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        unittable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(unittable);

        unitcombo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        unitcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Building", "Show All Units" }));
        unitcombo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                unitcomboAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        unitcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitcomboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Unit Room");

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton5.setText("Check Vacant");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton6.setText("Check Occupied");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UnitLayout = new javax.swing.GroupLayout(Unit);
        Unit.setLayout(UnitLayout);
        UnitLayout.setHorizontalGroup(
            UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnitLayout.createSequentialGroup()
                .addGroup(UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UnitLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unitroom, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UnitLayout.createSequentialGroup()
                                .addComponent(unitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton4))))
                    .addGroup(UnitLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton5)
                        .addGap(52, 52, 52)
                        .addComponent(jButton6))
                    .addGroup(UnitLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UnitLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel5)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        UnitLayout.setVerticalGroup(
            UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(unitcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(unitroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainHolder.add(Unit, "card3");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(ButtonHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainHolder.removeAll();
        MainHolder.repaint();
        MainHolder.revalidate();
    
        MainHolder.add(Building);        
        MainHolder.repaint();
        MainHolder.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainHolder.removeAll();
        MainHolder.repaint();
        MainHolder.revalidate();
    
        MainHolder.add(Unit);        
        MainHolder.repaint();
        MainHolder.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     new Vacant().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     new Occupy().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
            
            if(unitroom.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please fillup the unit room field","Error",JOptionPane.ERROR_MESSAGE);
            }else if(unitcombo.getSelectedItem().equals("Select Building")){
                JOptionPane.showMessageDialog(null, "Error Select Building","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                //Validations if unit number exist
                String unittext = unitroom.getText();
                String comboid = unitcombo.getSelectedItem().toString();
                String unitnumber = "select * from buildingunits where unitNumber ='"+unittext+"' and buildingName ='"+comboid+"'";               
                pst = conn.prepareStatement(unitnumber);
                rs = pst.executeQuery(unitnumber);
                
                if(rs.next() == true){
                    JOptionPane.showMessageDialog(null, "Unit number exist on this building","Error",JOptionPane.ERROR_MESSAGE);
                    
                }else{
                    //get the id of the building selected
                    String buildingid = "select * from buildings where buildingName = '"+comboid+"'";
                    pst = conn.prepareStatement(buildingid);
                    rs = pst.executeQuery(buildingid);
                    while(rs.next()){
                    //insert the unit number with building id
                    String buildingid2 = rs.getString("buildingID");
                    String sql = "Insert into buildingunits (buildingID,buildingName,unitNumber,unitStatus) values ('"+buildingid2+"',?,?,'vacant')";
                    pst = conn.prepareStatement(sql);
                    String combo = unitcombo.getSelectedItem().toString();
                    pst.setString(1, combo);
                    pst.setString(2, unitroom.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Unit Added");
                    UnitRoomTable(); 
                    unitroom.setText("");
                    }
                }
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
                //insert the building name
                if(building.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Please fill up Building","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    String addbuilding= "Insert into buildings (buildingName) values (?)";
                    pst = conn.prepareStatement(addbuilding);
                    pst.setString(1, building.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Building Added");
                    building.setText("");
                    Updatetable();
                    UnitCombo();
                    
                }
                 
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void unitcomboAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_unitcomboAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_unitcomboAncestorAdded

    private void unitcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitcomboActionPerformed
        UnitRoomTable();  
    }//GEN-LAST:event_unitcomboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Building;
    private javax.swing.JPanel ButtonHolder;
    private javax.swing.JPanel MainHolder;
    private javax.swing.JPanel Unit;
    private javax.swing.JTextField building;
    private javax.swing.JTable buildingtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> unitcombo;
    private javax.swing.JTextField unitroom;
    private javax.swing.JTable unittable;
    // End of variables declaration//GEN-END:variables
}
